services:
  db:
    image: postgres
    container_name: test-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - test-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: test-redis
    image: redis
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASE: ${REDIS_DB}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    # command: >
    #   --requirepass ${REDIS_PASSWORD}
    networks:
      - test-network
    depends_on:
      - db
    volumes:
      - redis_data:/data

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local

networks:
  test-network:
    driver: bridge
